version: '3.4'

services:
  skoruba.identityserver4.admin:
    image: ${DOCKER_REGISTRY-}skoruba-identityserver4-admin
    ports:
      - 9000:80
    build:
      context: .
      dockerfile: src/Skoruba.IdentityServer4.Admin/Dockerfile
    container_name: skoruba-identityserver4-admin
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:AdminConnection=Server=db.example.com;Database=IdentityServer4Admin;User Id=sa;Password=Password_123;MultipleActiveResultSets=true"
      - "AdminConfiguration:IdentityAdminBaseUrl=http://localhost:9000"
      - "AdminConfiguration:IdentityAdminRedirectUri=http://localhost:9000/signin-oidc"
      - "AdminConfiguration:IdentityServerBaseUrl=http://id.example.com"
    command: dotnet IdentityServer4Admin.dll /seed
    depends_on:
      - db
      - skoruba.identityserver4.sts.identity
    networks:
      default:
        aliases:
          - admin.example.com

  skoruba.identityserver4.sts.identity:
    image: ${DOCKER_REGISTRY-}skoruba-identityserver4-sts-identity
    ports:
      - 80:80
    build:
      context: .
      dockerfile: src/Skoruba.IdentityServer4.STS.Identity/Dockerfile
    container_name: skoruba-identityserver4-sts-identity
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:AdminConnection=Server=db.example.com;Database=IdentityServer4Admin;User Id=sa;Password=Password_123;MultipleActiveResultSets=true"
    depends_on:
      - db
    networks:
      default:
        aliases:
          - id.example.com

  db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - 1433
    container_name: skoruba-identityserver4-db
    environment:
      SA_PASSWORD: "Password_123"
      ACCEPT_EULA: "Y"
    networks:
      default:
        aliases:
          - db.example.com

networks:
  default:
    driver: bridge