version: '3.7'

services:
  skoruba.identityserver4.admin:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9000:80"

  skoruba.identityserver4.sts.identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"

